root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/worker"
  cmd = "go build -o ./tmp/worker ./cmd/worker && chmod +x ./tmp/worker"
  entrypoint = ["./tmp/worker"]
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
